{% set version = "2.0.2" %}

package:
  name: opennavsurf-bag
  version: {{ version }}

source:
  url: https://github.com/OpenNavigationSurface/BAG/archive/refs/tags/release-{{ version }}.tar.gz
  sha256: 35a184111dcace8aa538fc31c293042273589c0ddc23a676fc254606c9fd8c55

build:
  number: 1
  skip: true  # [py<38]

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - swig
  host:
    - hdf5
    - libxml2

outputs:
  - name: libbaglib
    script: install_lib.sh  # [unix]
    script: install_lib.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('libbaglib', max_pin='x.x') }}
    requirements:
      build:
        - cmake
        - ninja
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - catch2
      host:
        - hdf5
        - libxml2
    about:
      summary: The Bathymetric Attributed Grid (BAG) library
      license: BSD-3-Clause
      license_file: LICENSE.txt

  - name: bagpy
    script: install_python.sh  # [unix]
    script: install_python.bat  # [win]
    build:
      skip_compile_pyc:
        python/*.py
    requirements:
      build:
        - cmake
        - ninja
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - python  # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - swig
      host:
        - python
        - pip
        - setuptools
        - pytest
        - setuptools-scm
        - wheel
        - cmake-build-extension
        - hdf5
        - libxml2
        - {{ pin_subpackage('libbaglib', exact=True) }}
      run:
        - python
        - {{ pin_subpackage('libbaglib', exact=True) }}
    test:
      files:
        - run_test.py
      imports:
        - bagPy
      commands:
        - python run_test.py
    about:
      summary: Python wrapper for the Bathymetric Attributed Grid (BAG) library
      license: BSD-3-Clause
      license_file: LICENSE.txt

about:
  home: https://github.com/OpenNavigationSurface/BAG
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: |
    BAG consists of library code and examples required to read and write data in the Bathymetric Attributed 
    Grid (BAG) file format.

extra:
  recipe-maintainers:
    - selimnairb
